name: Code to pdf test
on: push
jobs:
    test-1:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v2
              with: 
                python-version: '3.x'
                #            - name: List files in the repository
                #              run: |
                #                ls 
                #                pwd
#            - name: Install dependencies
#              run: |
#                  python -m pip install --upgrade setuptools wheel
#                  sudo apt install wkhtmltopdf
            - name: Install package 
              run: python -m pip install  ./
